name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Sistem Gerecleri
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          pip install buildozer cython==0.29.33

      - name: APK Derle (Aidl Cozumu)
        run: |
          # Aidl hatasini engellemek icin GitHub'in hazir araclarini bagliyoruz
          mkdir -p ~/.buildozer/android/platform/android-sdk/build-tools
          ln -s $ANDROID_HOME/build-tools/34.0.0 ~/.buildozer/android/platform/android-sdk/build-tools/31.0.0
          
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          buildozer android debug

      - name: APK Yukle
        uses: actions/upload-artifact@v4
        with:
          name: IPTV-APK-Dosyam
          path: bin/*.apk
